apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: examxv2-backend-servicemonitor
  namespace: monitoring
  labels:
    app: examxv2-backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: examxv2-backend
  namespaceSelector:
    matchNames:
      - dev-examxv2
      - stg-examxv2
  endpoints:
    # Celery metrics endpoint
    - port: http
      path: /celery-metrics
      interval: 15s
      scheme: http
    # Django metrics endpoint  
    - port: http
      path: /metrics
      interval: 15s
      scheme: http