apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-bulk-export-worker
  labels:
    app: celery-bulk-export-worker
  annotations:
    kubernetes.io/change-cause: "Added change-cause annotation to deployment"
spec:
  # replicas: controlled by KEDA ScaledObject (scales from 0 to maxReplicaCount based on queue)
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 # Ensures zero downtime by not allowing any unavailable pods
  selector:
    matchLabels:
      app: celery-bulk-export-worker
  template:
    metadata:
      labels:
        app: celery-bulk-export-worker
    spec:
      serviceAccountName: examxv2-sa # Placeholder, to be overridden
      terminationGracePeriodSeconds: 30
      volumes:
        - name: examxv2-secrets-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "examxv2-backend-secrets"
        - name: examxv2-google-credentials
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: examxv2-google-credentials
        - name: examxv2-backend-storage
          persistentVolumeClaim:
            claimName: examxv2-backend-pvc
      containers:
        - name: celery-bulk-export-worker
          image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-backend:stg-20250814-132223-859cae893d229663024ed2546db378875707496e
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "1"
              memory: "8Gi"
            limits:
              cpu: "2"
              memory: "12Gi"
          command:
            - celery
            - -A
            - examx
            - worker
            - -P
            - gevent
            - -c
            - "2"
            - -Q
            - bulk_export
            - --loglevel=debug
            - --max-tasks-per-child=50
            - --max-memory-per-child=10000000
            - -E
          volumeMounts:
            - name: examxv2-secrets-volume
              mountPath: /mnt/secret-store
              readOnly: true
            - name: examxv2-backend-storage
              mountPath: /app/media
            - name: examxv2-google-credentials
              mountPath: /app/google-credentials.json
              subPath: google-credentials.json
          lifecycle:
            postStart:
              exec:
                command: ['cp', '-R', '/mnt/secret-store/.env', '/app/examx/.env']

